### PR TITLE
Feature/removing fairsale

### LINKED ISSUE #445: Remove fairsale from MVP release branch and subgraph deployment
After we merge into main and cut a release branch for the fixed price MVP release we should merge a feature branch to remove the fairsale page from routing as well as from sale summary cards on the /sales page.
Of course we wont be launching fairsales ourselves on the production contracts, however if one is launched accidentally then we need to make sure it doesnt appear to users in production who may be confused or even try to take part in the sale. 
Subgraph also needs this removed to prevent crashing that happens when launching sales. During this the subgraph endpoint should be updated to just aqua-xdai (not -next)

### PR DESCRIPTION
**Pull request by rossneilson**
## Description
Removing fairsale for MVP 0.1.1 release
Also removing contracts to use exported files from aqua-js, will add this to dev after also (I forgot in the previous PR)
Updated xdai subgraph endpoint

## Motivation and Context
Closes #445

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mprasanjith** [comment]
Two things we'll need to fix. I don't think these were introduced in this PR, but I'm leaving this comment here for visibility.

When you do a purchase, the order shows up fine, like below.

image

Let's keep this in mind, and go back to all sales. Notice that the sale card doesn't show any purchase data.

Now, let's refresh the page. The card now has my purchases shown nicely.

image

So first issue; We need to update the card to show the token purchases before refreshing the page. Just a minor tweak.

Now let's open the sale page again.

Screenshot 2021-09-08 at 19-11-14 Fixed Price Sale Token – FPST Aqua

Now the order history doesn't show up at all. That's the second issue.

I'll create separate issues for these for tracking.

**Comment by mprasanjith** [comment]
Btw do we have any idea why the Netlify builds failed? I don't think we should care, but just in case.

**Comment by rossneilson** [comment]
Nice spotting those bugs, we'll get them fixed for MVP
On netlify, I was thinking it was maybe because we are merging to main and not develop? But yeah, not important we could probably remove netlify

**Review by mprasanjith — APPROVED** [review]

**Comment by mprasanjith** [comment]
Updated the PR to fix #461.

**Comment by rossneilson** [comment]
For some reason, not sure if this was just something we didn't test recently, sales that I participated in but failed to be successful sales were not appearing in the closed tab under my sales or other sales. 
To fix this I removed the filtering on successful sales for the claims section and turned the "Bids won" into "Participated sales". 
In future we should add different types of token claims here for failed and successful.

**Pull request merged**
